version: "3"

services:
  database:
    env_file:
      - .env
    ports:
      - 5432:5432

  client:
    volumes:
      - ./client/build:/usr/share/nginx/html/
    env_file:
      - .env

  blop:
    volumes:
      - ./blop:/home/app/blop
      - /home/app/blop/node_modules
    command: ["npm", "run", "dev"]

  server:
    volumes:
      - ./server/:/home/app/server
    env_file:
      - .env

  gateway:
    volumes:
      - /home/app/gateway/node_modules
      - ./gateway/:/home/app/gateway
    command: ["npm", "run", "dev"]
    ports:
      # Expose graphql-playground localhost:4000
      - "4000:80"

  cms:
    volumes:
      - ./cms/src/web/profiles:/var/www/html/web/profiles
    env_file:
      - ./cms/.env

  cms_db:
    restart: always
    env_file:
      - .env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'

  processor:
    volumes:
      - ./processor/src/app:/app/app
