version: "3"

volumes:
  db-data:
    external: false

services:
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/db-data
      - ./database:/etc/cron.daily

  mongodb:
    image: mongo
    volumes:
      - ./processor-db:/data/db

  gateway:
    build: ./gateway

  blop:
   build: ./blop
   depends_on:
     - database
   env_file:
     - .env

  client:
    image: hasadna/open-pension-client
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - SERVICE_PORTS=80
    depends_on:
      - server

  server:
    image: hasadna/open-pension-server
    command: /bin/sh entrypoint.sh
    volumes:
      - ./logs/django:/home/app/server/logs
    depends_on:
      - database

  processor:
    build: ./processor
    command: /bin/sh entrypoint.sh
    volumes:
    - ./logs/processor:/home/app/processor/logs
    ports:
      - "9999:27107"
      - "1000:5000"
    depends_on:
    - mongodb

  cms:
    build: ./cms
