version: "3"

volumes:
  processor-db:
    external: false

services:
  gateway:
    build: ./gateway

  blop:
    build: ./blop
    depends_on:
      - database
    env_file:
      - .env

  client:
    image: hasadna/open-pension-client
    ports:
      - "80:80"
    environment:
      - SERVICE_PORTS=80

  processor:
    build: ./processor
    environment:
      - MONGO_URL=mongodb://processor_db:27017/
      - PYTHONUNBUFFERED=true
    depends_on:
      - processor_db

  processor_db:
    image: mongo
    volumes:
      - processor-db:/data/db

  cms:
    build: ./cms

  kafka:
    build: ./kafka
    environment: 
      - BROKER_ID=1
    depends_on: 
      - zookeeper

  kafka2:
    build: ./kafka
    environment: 
      - BROKER_ID=2
    depends_on: 
      - zookeeper

  zookeeper: 
    image: zookeeper:3.5
