version: "3"

services:
  database:
    env_file:
      - .env
    ports:
      - 5432:5432

  client:
    volumes:
      - ./client/dist:/usr/share/nginx/html/
    env_file:
      - .env

  blop:
    volumes:
      - /home/app/blop/node_modules
      - ./blop:/home/app/blop
    command: ["npm", "run", "dev"]

  server:
    volumes:
      - ./server/:/home/app/server
    env_file:
      - .env

  gateway:
    volumes:
      - /home/app/gateway/node_modules
      - ./gateway/:/home/app/gateway
    command: ["npm", "run", "dev"]
    ports:
      # Expose graphql-playground localhost:4000
      - "4000:80"

  cms:
    volumes:
      - /home/app/server/node_modules
      - ./cms/:/home/app/server
