version: "3"

volumes:
  application-db:
    external: false
  processor-db:
    external: false

services:
  gateway:
    image: hasadna/open-pension-gateway
    build: ./gateway

  application:
    image: hasadna/open-pension-application
    build: ./application
    depends_on:
      - application_db
    env_file:
      - ./application/.env

  application_db:
    image: postgres
    volumes:
      - application-db:/var/lib/postgresql/db-data

  client:
    image: hasadna/open-pension-client
    build: ./client
    ports:
      - "80:80"
    environment:
      - SERVICE_PORTS=80
    depends_on:
      - gateway

  processor:
    image: hasadna/open-pension-processor
    build: ./processor
    environment:
      - MONGO_URL=mongodb://processor_db:27017/
      - PYTHONUNBUFFERED=true
    depends_on:
      - processor_db

  processor_db:
    image: mongo
    volumes:
      - processor-db:/data/db

  cms:
    image: hasadna/open-pension-cms
    build: ./cms

  kafka:
    image: hasadna/open-pension-kafka
    build: ./kafka
    environment: 
      - BROKER_ID=1
    depends_on: 
      - zookeeper

  kafka2:
    image: hasadna/open-pension-kafka
    environment: 
      - BROKER_ID=2
    depends_on:
      - zookeeper

  zookeeper: 
    image: zookeeper:3.5
