version: "3.7"

services:
  client:
    volumes:
      - ./client/build:/usr/share/nginx/html/

  application:
    volumes:
      - ./application:/home/app
      - /home/app/node_modules
    command: ["npm", "run", "dev"]

  gateway:
    volumes:
      - /home/app/gateway/node_modules
      - ./gateway/:/home/app/gateway
    command: ["npm", "run", "dev"]
    ports:
      # Expose graphql-playground localhost:4000
      - "4000:80"

  cms:
    volumes:
      - ./cms/src/web/profiles:/var/www/html/web/profiles
    env_file:
      - ./cms/.env

  cms_db:
    restart: always
    env_file:
      - .env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'

  processor:
    volumes:
      - ./processor/src/app:/app/app
    ports:
      - "1000:80"

  processor_db:
    ports:
      - '27017:27017'
