version: "3"

services:
  database:
    env_file:
      - .env

  client:
    volumes:
      - ./client/:/home/app/client
    env_file:
      - .env

  server:
    volumes:
      - ./server/:/home/app/server
    env_file:
      - .env
