version: "3"

services:
  client:
    volumes:
      - ./client/build:/usr/share/nginx/html/
    env_file:
      - .env

  blop:
    volumes:
      - ./blop:/home/app/blop
      - /home/app/blop/node_modules
    command: ["npm", "run", "dev"]

  gateway:
    volumes:
      - /home/app/gateway/node_modules
      - ./gateway/:/home/app/gateway
    command: ["npm", "run", "dev"]
    ports:
      # Expose graphql-playground localhost:4000
      - "4000:80"

  cms:
    volumes:
      - /home/app/server/node_modules
      - ./cms/:/home/app/server

  processor:
    volumes:
      - ./processor/src/app:/app/app
    ports:
      - "1000:80"

  processor_db:
    ports:
      - '27017:27017'
